version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: syntri_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: syntri
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - whatsapp_agent_network

  # Optional: MongoDB Express for database management
  mongo-express:
    image: mongo-express:latest
    container_name: syntri_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
    depends_on:
      - mongodb
    networks:
      - whatsapp_agent_network

volumes:
  mongodb_data:

networks:
  whatsapp_agent_network:
    driver: bridge
